site_name: NLSE Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
  - mkdocs-jupyter:
      execute: false
      kernel_name: python3

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: quick_start.md
  - User Guide:
      - Physics Background: physics_problem.md
      - Solvers Overview: solvers_overview.md
      - Backends: backends.md
      - Callbacks: callbacks.md
      - Numerical Methods: numerical_methods.md
      - Examples Gallery: examples.md
  - Tutorial:
      - NLSE Tutorial: nlse_tutorial.ipynb
  - API Reference:
      - NLSE: reference/nlse.md
      - NLSE_1d: reference/nlse_1d.md
      - NLSE_3d: reference/nlse_3d.md
      - CNLSE: reference/cnlse.md
      - CNLSE_1d: reference/cnlse_1d.md
      - GPE: reference/gpe.md
      - DDGPE: reference/ddgpe.md
      - Callbacks: reference/callbacks.md
      - Backends: reference/backends.md
      - Kernels: reference/kernels.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
