"""Sphinx configuration for the NLSE documentation.

Built with MyST, so every narrative page stays markdown rather than being
rewritten as reStructuredText, and the tutorial notebook is a page like any
other. The API section is generated by sphinx-autoapi, which *parses* the
source instead of importing it -- this package imports cupy, pyopencl or mlx
depending on the backend, and none of the three installs on a documentation
runner.

Maths is handled in one place for every kind of page. That is not a detail:
under the previous toolchain markdown and notebooks went through different
renderers with different delimiters, and the tutorial published every one of
its formulas as LaTeX source for as long as the page existed.
"""

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The benchmark examples read this and take a short sweep, so the gallery
# can show the graph they draw without the build taking minutes on it.
os.environ.setdefault("NLSE_DOCS_BUILD", "1")

project = "NLSE"
author = "Tangui Aladjidi"
copyright = "2026, Tangui Aladjidi"

# Read from the package rather than repeating it. tests/test_packaging.py
# holds __init__.py and pyproject.toml to the same string.
_version = re.search(
    r'__version__\s*=\s*"([^"]+)"',
    (ROOT / "NLSE" / "__init__.py").read_text(encoding="utf-8"),
)
release = version = _version.group(1) if _version else "unknown"

extensions = [
    "myst_nb",  # markdown and notebook pages, and brings in myst_parser
    "autoapi.extension",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",  # the numpy docstrings this package enforces
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    # Writes .nojekyll into the build. GitHub Pages otherwise runs the
    # output through Jekyll, which drops every directory beginning with
    # an underscore -- _static and _images, so the site would deploy
    # with no stylesheet, no MathJax and no figures.
    "sphinx.ext.githubpages",
    "sphinx_copybutton",
    "sphinx_gallery.gen_gallery",
]

# The gallery runs every example when the docs are built and keeps the figures
# it produced, so the picture on the page is the one that script makes today
# rather than one committed months ago.
sphinx_gallery_conf = {
    "examples_dirs": "../examples",
    "gallery_dirs": "auto_examples",
    # Executed unless named here, and only two are. Both call sys.exit() when
    # what they need is absent -- CuPy for one, data from a benchmark run for
    # the other -- and sphinx-gallery lets SystemExit propagate, so an example
    # that exits takes the whole build down with it, silently and with a zero
    # status. The benchmark sweeps *do* run: they read NLSE_DOCS_BUILD and
    # take a short range, so the gallery shows a real graph rather than a
    # placeholder.
    "filename_pattern": r"^(?!.*(juliaGPE_vs_NLSE|profile_cupy)).*$",
    "ignore_pattern": r"_output\.py",
    "within_subsection_order": "FileNameSortKey",
    "download_all_examples": False,
    "remove_config_comments": True,
    # (True, "html5") writes an mp4 through ffmpeg. The alternative, jshtml,
    # embeds every frame as base64 inside the page: the tutorial notebook
    # produced 78 MB that way, against a 20 MB limit, for one animation.
    "matplotlib_animations": (True, "html5"),
    "thumbnail_size": (400, 280),
}

# dollarmath is what makes $...$ and $$...$$ work in markdown *and* in the
# notebook, through one renderer. amsmath covers align/gather environments.
myst_enable_extensions = [
    "dollarmath",
    "amsmath",
    "colon_fence",
    "deflist",
    "attrs_inline",
]
myst_heading_anchors = 3

# The tutorial ships with its outputs and is not re-run at build time: it
# takes minutes and needs a GPU to be interesting.
nb_execution_mode = "off"

autoapi_dirs = [str(ROOT / "NLSE")]
autoapi_type = "python"
autoapi_root = "api"
autoapi_keep_files = False
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
]
# The kernels are left out on purpose. They are backend-specific numerics that
# nobody calls directly -- every one of them is reached through a solver -- and
# their docstrings are written for a reader rather than for docutils: "|A|^2"
# is a substitution reference in reStructuredText, so autoapi warns on every
# one. Documenting them would mean rewriting physics prose to suit a parser.
autoapi_ignore = ["*/kernels/*"]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

templates_path = ["_templates"]
# myst-nb registers .ipynb as a source suffix, and sphinx-gallery writes one
# next to every .rst it generates, so Sphinx sees two candidate documents
# per example. The notebooks are downloads, not pages.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "README.md",
    "auto_examples/**/*.ipynb",
    "auto_examples/*.ipynb",
]

html_theme = "furo"
html_title = f"NLSE {version}"
html_static_path = ["_static"]

# MathJax is served from here, not from a CDN, and that is the point rather
# than a detail: a <script> pointed at someone else's host runs whatever that
# host decides to serve in the browser of everyone who reads these pages. The
# entry this replaced was polyfill.io, which was sold in 2024 and began
# serving malware. See _static/mathjax/VENDORED.md for the version and how to
# update it. Sphinx would otherwise load MathJax from jsdelivr.
mathjax_path = "mathjax/tex-mml-chtml.js"
html_theme_options = {
    "source_repository": "https://github.com/taladjidi/NLSE/",
    "source_branch": "main",
    "source_directory": "docs/",
}

# The kernels are deliberately not in the API section, so the imports of them
# from backends and __init__ cannot resolve. That is the exclusion working,
# not a problem to fix.
suppress_warnings = ["myst.header", "autoapi.python_import_resolution"]
