"""In-tree PEP 517 build backend that clears the stale build/ staging area.

setuptools stages a build through ``build/lib/`` and copies the current
sources over whatever an earlier build left there, rather than starting
clean. A checkout that once held a different layout therefore keeps
shipping the old modules: they sit in ``build/lib/NLSE/`` and get zipped
into every subsequent wheel, where they shadow the real package. That is
how the pre-2.3 flat layout ended up inside NLSE 2.3.0 wheels.

Excluding ``build*`` from ``packages.find`` does not help, because
``packages.find`` never looks there — the files are picked up from the
staging directory, after discovery. The only reliable fix is to clear the
directory before each build, which is what this backend does before
delegating everything to setuptools.

The same applies to ``*.egg-info/SOURCES.txt``, which caches the list of
files to ship and only ever grows: once a file has been recorded there it
keeps appearing in sdists even after MANIFEST.in stops asking for it, and
a MANIFEST.in change that *removes* a file appears to have no effect.

NLSE is pure Python, so nothing is ever recompiled and a clean stage costs
only a file copy.
"""

import shutil
from pathlib import Path

from setuptools import build_meta as _setuptools

_PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Hooks that only inspect metadata are passed straight through.
get_requires_for_build_wheel = _setuptools.get_requires_for_build_wheel
get_requires_for_build_sdist = _setuptools.get_requires_for_build_sdist
get_requires_for_build_editable = _setuptools.get_requires_for_build_editable
prepare_metadata_for_build_wheel = _setuptools.prepare_metadata_for_build_wheel
prepare_metadata_for_build_editable = _setuptools.prepare_metadata_for_build_editable


def _clear_stale_build() -> None:
    """Delete the staging directory and the cached sdist file list.

    Both are regenerated by the build. Editable installs are unaffected:
    they resolve through the PEP 660 finder in site-packages, not through
    the source tree's egg-info.
    """
    shutil.rmtree(_PROJECT_ROOT / "build", ignore_errors=True)
    for egg_info in _PROJECT_ROOT.glob("*.egg-info"):
        shutil.rmtree(egg_info, ignore_errors=True)


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    """Build a wheel from a cleared staging directory."""
    _clear_stale_build()
    return _setuptools.build_wheel(wheel_directory, config_settings, metadata_directory)


def build_sdist(sdist_directory, config_settings=None):
    """Build an sdist from a cleared staging directory."""
    _clear_stale_build()
    return _setuptools.build_sdist(sdist_directory, config_settings)


def build_editable(wheel_directory, config_settings=None, metadata_directory=None):
    """Build an editable wheel from a cleared staging directory."""
    _clear_stale_build()
    return _setuptools.build_editable(
        wheel_directory, config_settings, metadata_directory
    )
